version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - dev-movie

  redis:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev-movie

networks:
  dev-movie:
    

# docker compose up -d
# docker compose down
# docker compose 
# docker compose up -d  mongodb -d
# docker exec -it redis redis-cli
# KEYS *
# GET key (lay ra key)